name: Build Application

on:
    push:
      branches:
        - build  # 指定触发工作流的分支名称

jobs:
  build-macos:
    runs-on: macOS-latest
    env:
      ARCHFLAGS: "-arch x86_64"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # 安装PyInstaller
        pip install pyinstaller
    - name: Build with PyInstaller (macOS)
      run: |
        pyinstaller --onefile --windowed github.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: macOS-Build
        path: dist  # 根据实际路径修改

  build-windows:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: windows-Build
        path: src/dist/windows
